import type { Course } from '@/interfaces/course'

export const data: Array<Course> = [
  {
    id: 1,
    cover: '/images/courses/jairaj.jpg',
    title: 'Jairaj Bhattacharya',
    // rating: 5,
    // ratingCount: 8,
    // price: 25,
    // category: '',
    desc: 'Ashoka taught me how building a great eco-system can mobilize value. Visionary founders, exemplary faculty, and talented students create an N-square effect on the ecosystem. Giving back to Ashoka will catalyze this further and unlock value for talented individuals getting scholarships and taking risks that symbolizes the true spirit of entrepreneurship and change-makers.',
    position: "Founder and Managing Director, Convegenius, YIF'12",
  },
  {
    id: 2,
    cover: '/images/courses/Mahesh.jpg',
    title: 'Mahesh Jakhotia',
    // rating: 5,
    // ratingCount: 15,
    // price: 20,
    // category: '',
    desc: 'Being a part of YIF was a life-changing decision for me, both professionally and personally. It would be my ultimate joy to see more and more people experience YIF/Ashoka. Giving back is one of the avenues, which lets me fulfill this desire! Glad to play a very small role in this',
    position: "Co-founder Bijak, YIF'12",
  },
  {
    id: 3,
    cover: '/images/courses/Natasha.jpg',
    title: 'Natasha Zarine',
    // rating: 4,
    // ratingCount: 7,
    // price: 30,
    // category: '',
    desc: "What I receive from the fellowship and all thoose who made it a reality, is boundless. I can only strive to give forward in the same spirit as those from whom I have received... And contribute in my small way so that more and more students get to experience Ashoka's truly inspiring education",
    position: "Co-founder and Managing Director, EcoSattva Environmental Solutions, YIF'13",
  },
  // {
  //   id: 4,
  //   cover: '/images/courses/true-agency-o4UhdLv5jbQ-unsplash.jpg',
  //   title: 'The Complete Guide Docker and Kubernetes',
  //   rating: 4,
  //   ratingCount: 12,
  //   price: 30,
  //   category: 'Intermediate',
  //   desc: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
  // },
  // {
  //   id: 5,
  //   cover: '/images/courses/stillness-inmotion-Jh6aQX-25Uo-unsplash.jpg',
  //   title: 'Modern React with MUI & Redux',
  //   rating: 4,
  //   ratingCount: 32,
  //   price: 35,
  //   category: 'Intermediate',
  //   desc: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
  // },
  // {
  //   id: 6,
  //   cover: '/images/courses/stillness-inmotion-YSCCnRGrD-4-unsplash.jpg',
  //   title: 'Ethical Hacking Bootcamp Zero to Mastery',
  //   rating: 5,
  //   ratingCount: 14,
  //   price: 35,
  //   category: 'Beginner',
  //   desc: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
  // },
  // {
  //   id: 7,
  //   cover: '/images/courses/grovemade-RvPDe41lYBA-unsplash.jpg',
  //   title: 'Adobe Lightroom For Beginners: Complete Photo Editing',
  //   rating: 4,
  //   ratingCount: 6,
  //   price: 25,
  //   category: 'Beginner',
  //   desc: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
  // },
]
